# Generated by Django 2.0.1 on 2018-01-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='repeat',
            field=models.CharField(default='MWF', max_length=100),
            preserve_default=False,
        ),
    ]
