# Generated by Django 2.0.1 on 2018-01-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giver', '0002_shift_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end',
            field=models.TimeField(verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start',
            field=models.TimeField(verbose_name='start'),
        ),
    ]
