# Generated by Django 2.0.1 on 2018-01-22 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giver', '0003_auto_20180119_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarycaregiver',
            name='charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='giver.Charge'),
        ),
    ]
