# Generated by Django 2.0.1 on 2018-02-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giver', '0004_primarycaregiver_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='extras',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='status',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
